include = ["**/*.toml"]
exclude = ["**/*nested-1000.toml", "**/node_modules/**", "**/invalid/*", "test-data/analytics/**"]

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true
