[package]
authors = ["tamasfe"]
description = "A CLI for Taplo TOML toolkit"
license = "MIT"
edition = "2018"
name = "taplo-cli"
version = "0.6.0"
homepage = "https://taplo.tamasfe.dev"
repository = "https://github.com/tamasfe/taplo"
categories = ["development-tools", "command-line-utilities"]
keywords = ["toml", "linter", "formatter"]

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["lsp"]
lsp = ["taplo-lsp"]

[dependencies]
lsp-async-stub = { version = "0.4.1", path = "../lsp-async-stub", features = [
    "tokio-tcp",
    "tokio-stdio",
] }
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "3.0.0", features = ["derive", "cargo"] }
futures = "0.3"
glob = "0.3"
hex = "0.4"
once_cell = "1.4"
pretty-lint = { version = "0.1" }
regex = "1.4"
reqwest = { version = "0.11.4", features = ["json"] }
schemars = "0.8"
serde = "1"
serde_json = "1"
sha2 = "0.10"
taplo = { version = "0.8.0", path = "../taplo", features = [
    "serde",
] }
taplo-lsp = { path = "../taplo-lsp", optional = true }
time = { version = "0.3", features = ["parsing"] }
toml = "0.5"
tracing-subscriber = { version = "0.3.7", features = ["env-filter"] }
tracing = "0.1.29"
atty = "0.2.14"
taplo-common = { version = "0.1.0", path = "../taplo-common" }
codespan-reporting = "0.11.1"
itertools = "0.10.3"
async-ctrlc = { version = "1.2.0", features = ["stream"] }
url = "2.2.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
console_error_panic_hook = { version = "0.1" }

[[bin]]
name = "taplo"
path = "bin/taplo.rs"
