[package]
authors = ["tamasf97 <tamasf97@outlook.com>"]
description = "Language server for Taplo"
edition = "2018"
name = "taplo-lsp"
version = "0.2.1"
license = "MIT"
homepage = "https://taplo.tamasfe.dev"
repository = "https://github.com/tamasfe/taplo"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
anyhow = "1"
futures = "0.3.5"
indexmap = { version = "1.6", features = ["serde"] }
itertools = "0.10.3"
lsp-async-stub = { version = "0.4.1", path = "../lsp-async-stub" }
lsp-types = { version = "0.91.0", features = ["proposed"] }
once_cell = "1.5"
parking_lot = "0.11.2"
reqwest = { version = "0.11.4", features = ["json"] }
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
taplo = { version = "0.8.0", path = "../taplo", features = [
    "serde",
] }
taplo-common = { path = "../taplo-common" }
time = { version = "0.3", features = ["formatting", "parsing"] }
toml = "0.5"
tracing = "0.1.29"
