[package]
authors = ["tamasfe"]
categories = ["parser-implementations", "parsing"]
description = "A TOML parser, analyzer and formatter library"
edition = "2018"
homepage = "https://taplo.tamasfe.dev"
keywords = ["toml", "parser", "formatter", "linter"]
license = "MIT"
name = "taplo"
readme = "../README.md"
repository = "https://github.com/tamasfe/taplo"
version = "0.8.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["serde"]
schema = ["schemars"]

[dependencies]
glob = "0.3"
logos = "0.12.0"
regex = "1.5.4"
rowan = "0.15.3"
semver = { version = "1.0.3", features = ["serde"] }

time = { version = "0.3.3", features = [
    "parsing",
    "formatting",
    "macros",
] }

ahash = "0.7.6"
arc-swap = "1.5.0"
either = "1.6.1"
enum-as-inner = "0.3.3"
from_variants = "0.6.0"
itertools = "0.10.3"
once_cell = "1.9.0"
parking_lot = "0.12.0"
schemars = { version = "0.8.3", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
# TODO
serde_json = "1"
thiserror = "1.0.30"

[dev-dependencies]
assert-json-diff = "2"
criterion = "0.3"
difference = "2.0.0"
serde_json = "1"
toml = "0.5"

[package.metadata.docs.rs]
features = ["serde", "schema"]

[[bench]]
name = "parser"
harness = false
